version: '3.3'
services:
  virtual-temple:
    #hostname:         virtual-temple
    #container_name:  "virtual-temple"
    image: "innovanon/virtual-temple:latest"
    networks:
      innovanon:
        aliases:
          - virtual-temple
    ports:
      - "31443:31443"
    volumes:
      - innovanon:/usr/local/lib/node_modules/virtual-temple/ssl:ro
    deploy:
      mode: replicated
      replicas: 2
      #update-delay: 10s

networks:
  innovanon:

volumes:
  innovanon:

