version: '3.3'
services:
  virtual-temple:
    #hostname:         virtual-temple
    #container_name:  "virtual-temple"
    image: "innovanon/virtual-temple:latest"
    networks:
      virtual-temple:
        aliases:
          - virtual-temple
    ports:
      - "31443:31443"
    #volumes:
    #  - innovanon:/usr/local/lib/node_modules/virtual-temple/ssl:ro
    deploy:
      mode: replicated
      replicas: 1
      #update-delay: 10s
    secrets:
      - key.pem
      - cert.pem

networks:
  virtual-temple:

#volumes:
#  innovanon:

secrets:
  key.pem:
    file: ./secrets/key.pem
  cert.pem:
    file: ./secrets/cert.pem

