#! /usr/bin/env bash
set -euo pipefail

npm install -g --production virtual-temple
cd /usr/lib/node_modules/virtual-temple

# -l
HOME=/srv exec             \
chpst -u nobody:nogroup -- \
npm start 2>&1

