# https://circleci.com/blog/automatically-deploy-a-gatsby-site-to-firebase-hosting/
# CircleCI Firebase Deployment Config

version: 2.1

orbs:
  slack: circleci/slack@4.1.3

jobs:
  build-test-and-notify:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/circleci-VirtualTemple
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-

      - run:
          name: Install Dependencies
          command: |
            #npm install --production
            #npm ci --only=production
            npm ci
      - run:
          name: Run Tests
          command: npm test

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      #- run:
      #    name: Gatsby Build
      #    command: npm run build
      - run:
          name: Autoversioning
          command: |
            git config --global user.email "$GITHUB_EMAIL"
            git config --global user.name  "$GITHUB_NAME"
            echo "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com" > ~/.git-credentials
            #npm version patch
            
            majmin=`grep '^ *"version" *: *' package.json | grep -o '[0-9]*\.[0-9]*' | head -n 1`

            [ ! -z "`git tag`" ]                                   || git tag v$manmin
            git describe --tags --long | grep -q '^v[^.]*\.[^.-]*' || git tag v$majmin

            revisioncount=`git log --oneline | wc -l`
            VERSION="$majmin.$revisioncount"

            npm version "$VERSION"
      - run:
          name: Authenticate with Registry
          # --only hosting ?
          #command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
          command: |
            #./node_modules/.bin/firebase login --reauth --token "$FIREBASE_TOKEN"
            #./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --non-interactive --only hosting
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: # https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d
          name: For the Love of God
          command: |
            #if find . -name .npmignore | grep -q . ; then false ; else true ; fi
            npm pack
            tar -vtf *.tgz | tee audit
            if grep -q -e run -e .circleci -e '\\.pem' audit ; then false ; else true ; fi
            rm  -v   *.tgz   audit
      - run:
          name: Publish Package
          command: |
            npm publish
      - run:
          name: Notify DockerHub
          command: |
            curl -X POST "$DOCKERHUB_TRIGGER"
      - slack/status:
          event: fail
          template: basic_fail_1

workflows:
  #version: 2
  deploy_and_notify:
    jobs:
      - build-test-and-notify:
          filters:
            branches:
              ignore: gh-pages
          context:
            - github personal access token

