# https://circleci.com/blog/automatically-deploy-a-gatsby-site-to-firebase-hosting/
# CircleCI Firebase Deployment Config
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/circleci-VirtualTemple
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-

      - run:
          name: Install Dependencies
          command: |
            #npm install --production
            npm ci
      - run:
          name: Run Tests
          command: npm test

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      #- run:
      #    name: Gatsby Build
      #    command: npm run build
      - run:
          name: Autoversioning
          command: |
            git config --global user.email "$GITHUB_EMAIL"
            git config --global user.name  "$GITHUB_NAME"
            echo "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com" > ~/.git-credentials
            #npm version patch
            majmin=`grep '^ *"version" *: *' package.json | grep -o '[0-9]*\.[0-9]*'`

            [ ! -z "`git tag`" ]                                   || git tag v$manmin
            git describe --tags --long | grep -q '^v[^.]*\.[^.-]*' || git tag v$majmin

            revisioncount=`git log --oneline | wc -l`
            cleanversion="`git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' | sed s/^v//`"
            VERSION="$cleanversion.$revisioncount"
            npm version "$VERSION"
      - run:
          name: Authenticate with Registry
          # --only hosting ?
          #command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
          command: |
            #./node_modules/.bin/firebase login --reauth --token "$FIREBASE_TOKEN"
            #./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --non-interactive --only hosting
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish Package
          command: |
            npm publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
